repo: src/v8
patches:
-
  owners: alespergl
  file: build_gn.patch
  description: null
-
  owners: zcbenz
  file: array_buffer.patch
  description: null
-
  owners: zcbenz
  file: ostreams.patch
  description: null
-
  owners: alexeykuzmin,alespergl
  file: export_platform.patch
  description: |
    v8::Platform::SystemClockTimeMillis must be exported so that node::NodePlatform can call it
-
  owners: alespergl
  file: dcheck.patch
  description: null
-
  owners: nitsakh
  file: disable-warning-win.patch
  description:
    Disable unit test windows build warning
