repo: src/third_party/webrtc
patches:
-
  owners: alexeykuzmin
  file: backport_7f90e2cceda.patch
  description: "https://webrtc-review.googlesource.com/9384"
-
  owners: alexeykuzmin
  file: fix_laggy_mouse_during_desktop_capture.patch
  description: null
-
  owners: null
  file: webrtc-desktop_capturer_mac.patch
  description: null
-
  owners: null
  file: webrtc-rwlock_null.patch
  description: null
-
  owners: nitsakh
  file: disable-warning-win.patch
  description:
    Disable windows warning
-
  owners: ajmacd
  file: fix_jitter_buffer_with_opus_dtx.patch
  description: "https://webrtc-review.googlesource.com/c/src/+/18181"
-
  owners: alexeykuzmin
  file: backport_a157e0809.patch
  description:
    VP9 temporal index bounds check. Landed in 67.0.3396.62.
    https://webrtc-review.googlesource.com/73701
